### PR TITLE
Update VelocityControl

### PR DESCRIPTION
**Pull request by ElBananaa**
Updated the plugin to support the new SoundNotify feature with velocity.

**CHANGES HAVE NOT BEEN TESTED AS I DON'T HAVE A VELOCITY SETUP**

### CODE REVIEW

**Comment by kangarko** [comment]
Sorry, I can't approve non-tested changes, please either get the setup or wait for james to submit.

**Comment by ElBananaa** [comment]
> Sorry, I can't approve non-tested changes, please either get the setup or wait for james to submit.

Ik, which is why I pushed 3.9.4 as a pre-release on my repo.
Unfortunately I have no ways to try the changes on a network setup as I only have a single local test server.

**Comment by kangarko** [comment]
Can't you just create multiple servers on your local computer? This is how I used to test BungeeCord. You'd only change the port for Velocity/Bungee and then connect them together.,

**Comment by kangarko** [comment]
I am sorry but I am unable to help you with that since I myself don't have enough experience with Velocity. If James is not answering maybe I can post on our Discord again to find someone skilled but he was really good, best would be if you guys get a test environment and push changes

**Comment by james090500** [comment]
I will be happy to look at this when I have time. @ElBananaa feel free to ping me on discord if you need help setting up velocity.

**Comment by ElBananaa** [comment]
> I will be happy to look at this when I have time. @ElBananaa feel free to ping me on discord if you need help setting up velocity.

I don't have troubles with setting up velocity, but with running it on my local computer, but thanks for the offer.

**Comment by kangarko** [comment]
James replied to me on Discord, just sent him a message and he'll help you with setting up a local test environment.

**Comment by james090500** [comment]
Thanks for the contribution

**Pull request merged**
